### ISSUE TITLE
Tooltips on local law changes

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-citymap#122]
Street names, corners, squares, etc need tooltips on hover.  Format should be {name} - {effective date}

Consider adding resolution number if available in the data.

**Comment by andycochran** [comment]
On click, the popup could show a link to Councilmatic: 
https://laws.council.nyc.gov/legislation/res-{intronumbe}-{intro_year}/

**Comment by andycochran** [comment]
Local Law name changes should show in the popup, if the latlon intersects with one. The popup can link to the Councilmatic intro.

**Comment by aenglis** [comment]
No resolution number in data but has intro number and year.

**Comment by aenglis** [comment]
Format should be {officialname} - {honoraryname} - {LL_limits}. All data included in name changes features are effective so effective dates don't need to be shown.

**Comment by chriswhong** [comment]
- Add label layer for `honoraryname`
- Add tooltip using format described above
- Add to popup and include a link to council resolution

**Comment by chriswhong** [comment]
Tooltips added for `honoraryna`.  Where `honoraryna` does not exist, it uses `officialna`
