### ISSUE TITLE
Visualize Paper Streets

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-citymap#136]
Mapped streets that haven't been built. Show as a "squiggle" or "zig zag" line.

**Comment by aenglis** [comment]
Paper Street Tooltip Text: A term used for a street that is officially mapped but is not built and only appears on "paper maps".

**Comment by chriswhong** [comment]
- Add 2 toggleable layergroups (step-stair streets, paper streets)
- Work with @aenglis on symbology

**Comment by andycochran** [comment]
We'll visualize these similarly to the lines layer in the Local Law Name layer group.
