### ISSUE TITLE
Add Sketchmaps for unfiled maps

### ISSUE THREAD

**Issue by srlenard** [NYCPlanning/labs-citymap#158]
Andrew has the shapes and pdfs ready.  Need to add a legend item labelled "Pending Alterations" with a tooltip that says "These changes to the City Map have been approved by the City Planning Commission and City Council, but have not yet been fully implemented.  They are not yet official and the City Map does not reflect these changes to yet, but they may be implemented by the City without further public review."  The shapes should be a different color from the filed alteration maps.

**Comment by chriswhong** [comment]
Add a new layergroup for "adopted and pending" amendments.

**Comment by allthesignals** [comment]
@aenglis can you get me the PDFs for this?

**Comment by allthesignals** [comment]
> Add new list of entries into popup

Should it just split out the pending/adopted amendments into a separate list?

**Comment by allthesignals** [comment]
<img width="249" alt="screen shot 2018-05-21 at 12 46 20 pm" src="https://user-images.githubusercontent.com/5004319/40319139-1268a7d8-5cf5-11e8-9c1a-24be4b02dc0b.png">

Current branch 158-sketchmaps groups by status - need input on what this should be? Also need to understand whether the list should group by _any_ status or group by only certain groups of statuses? Not sure.

**Comment by allthesignals** [comment]
I have the feature working fully in this branch: https://github.com/NYCPlanning/labs-citymap/tree/158-sketchmaps

I think it just could use some design review from @andycochran - specifically:
1 - pending alterations color
2 - styling of grouped list items in popup.

Thanks!

**Comment by allthesignals** [comment]
Files have been uploaded to DO spaces
