### ISSUE TITLE
Exaggerate stair-step street at large zoom scales

### ISSUE THREAD

**Issue by aenglis** [NYCPlanning/labs-citymap#185]
Because there are not many step-stair streets around the city, the symbology needs to pop more when viewed from a citywide scale to allow the user to easily identify their locations.

**Comment by chriswhong** [comment]
I have an idea for this, I think when zoomed below a certain level we could show a large transparent circle around each stair street (a halo, if you will) which would be clearly visible... the features for the stair streets are small, so making them bolder when zoomed out will be tough.
