### ISSUE TITLE
Alteration layer is clickable when not turned on

### ISSUE THREAD

**Issue by aenglis** [NYCPlanning/labs-citymap#187]
When clicking on map when alteration map layer is turned off the user still get results for available or not available map for the location. Can we have it where the alteration maps are clickable only when the layer is turned on and visible in the map?

**Comment by andycochran** [comment]
We discussed this early on and decided that the popup should always show all info, regardless of which layers are on. This is mostly because you're not clicking on features, you're clicking on a point. The popup is not for the alteration, it's for the latlon.

**Comment by aenglis** [comment]
Ok, I was probably out on that one. Thanks for the clarification.

ANDREW ENGLISH
CAD/GIS SPECIALIST and CITY PLANNER III

NYC DEPT. OF CITY PLANNING
120 BROADWAY, 30TH FLOOR • NEW YORK, NY 10271
212-720-3292 I AENGLIS@PLANNING.NYC.GOV<mailto:AENGLIS@PLANNING.NYC.GOV>
[cid:image001.png@01CE44CC.0CAF5F40]<http://www.twitter.com/nycplanning>Follow us on Twitter @NYCPlanning<http://www.twitter.com/nycplanning>
www.nyc.gov/planning<http://www.dcp.nycnet/dcpcommons/downloads/word/home/www.nyc.gov/planning>
