### ISSUE TITLE
Build Error: Ember Decorators / IS_EMBER_2

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-citymap#189]
In trying to upgrade `mapbox-gl` from `^0.44.0` to `^0.45.0`, I wiped my node modules. Now I cannot run the app because Ember Decorators causes the `IS_EMBER_2 ` build error. 

![image](https://user-images.githubusercontent.com/409279/40740489-fff27c86-6416-11e8-9257-0c2e504f6c1c.png)

This could be related to https://github.com/ember-decorators/ember-decorators/issues/238? I tried bumping `"@ember-decorators/argument": "0.8.13"` to `0.8.15` as mentioned there. No luck.

**Comment by allthesignals** [comment]
Hmmm this looks really familiar - I’ll take a look

**Comment by allthesignals** [comment]
There are weirdly two packages that depend on decorator arguments, which I think is font awesome

**Comment by allthesignals** [comment]
@andycochran I bumped mapbox-gl to ^0.45.0 off of the develop branch, but can't reproduce the error... can you make the change off a clean branch off of develop?

**Comment by andycochran** [comment]
Odd. That's exactly what I had done. Worked this time. Closing.
