### ISSUE TITLE
Draft Wireframe

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-citymap#20]
Could we start with a draft wireframe to get us going on layout and what needs to happen? Nothing fancy, just high-level.

**Comment by andycochran** [comment]
https://docs.google.com/drawings/d/1aYYNilujnVGf1BrL3Sw8K7cnb7LG38yzjKkR6waWM7I/edit?usp=sharing

![image](https://user-images.githubusercontent.com/409279/38271917-befe78bc-3755-11e8-8f9c-bafac465c209.png)

**Comment by allthesignals** [comment]
I think we can TDD a basic shell of this more easily

**Comment by andycochran** [comment]
Prob needs a content area like ZoLa for welcome/disclaimer/about/etc…

![image](https://user-images.githubusercontent.com/409279/38273621-6fbd14a2-375a-11e8-91d3-be5623378961.png)

**Comment by allthesignals** [comment]
Test statements:
 - [ ] "It should collapse/expand City Map layers"
 - [ ] "It should collapse/expand Other Layers"
 - [ ] "Toggle icon should switch off / on when clicked"
 - [ ] "It should close info pane when clicking"
 - [ ] "Toggle state should honor query params"
