### ISSUE TITLE
User can view and toggle primary city map vector layers on a web map

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-citymap#3]
- [ ] Map Change Index (NYMI) (contains links to PDF)
- [x] Digital City Map (DCM)
- [ ] Legal Street Names
- [ ] Points, Areas, Streets
- [x] Digital City Map Street Centerlines (DCMSCL)
- [x] Arterials and Major Streets
- [x] Bulkheads and Pier Lines

Implied task: Andrew E will refine the datasets before loading

**Comment by allthesignals** [comment]
Related to architecture issues in #9. Implied content / layout design task. Need to decide which layers are on by default, which depends on having the data and seeing.

**Comment by allthesignals** [comment]
Alright, I think there are a few left here. `Map Change Index (NYMI) (contains links to PDF)` - need to do the linking for this still.
