### ISSUE TITLE
User can see an "about this point" UI on click

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-citymap#30]
This UI will be composed for a given lat/lon:
- [ ] Listing amendments.
- [ ] On hovering a list item, highlight the corresponding geometry on the map
- [ ] Include project name, date, link to PDF, link to ZAP (if applicable), link to CPC reports, status (approved but not filed, approved and filed)
- [ ] Show intersecting lot, Show this location in ZoLa

Note:  When the user is moving the mouse over the map, if it is above an amendment, make the cursor a pointer, but do not highlight anything...
Clicking that lat/lon will open a popup with the above info, showing things that intersect with that point.

**Comment by allthesignals** [comment]
@chriswhong 
This should be doable through the  current API setup (there's a hook for layerMouseClick). You can handle it through the application controller.

Only exception:
> On hovering a list item, highlight the corresponding geometry on the map
Will have to figure out a way to deal with this. One possibility is making this a domain-specific (citymap app specific) functionality. Hovering over specific list items in your popup component can trigger a secondary hover layer that you will setup in the application handlebars. Something liek this:

```handlebars
    {{#main-map
      id='main-map'
      initOptions=initMapOptions
      mapLoaded=(action 'handleMapLoad') as |map|}}
    {{!-- other labs-layers stuff --}}

    {{!-- setup your custom hover detail here --}}
    {{map.layer options=specialHoverLayerCoonfig}}
    {{/main-map}}
```

This approach means we won't have to built out the API more without knowning enough about this particular use-case.

**Comment by andycochran** [comment]
Moving the unfinished parts of this issue to separate issues…
