### ISSUE TITLE
Show tooltip on hover of citymap vector layers

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-citymap#36]

**Comment by allthesignals** [comment]
Proposed API:
```handlebars
    {{#main-map
      id='main-map'
      initOptions=initMapOptions
      mapLoaded=(action 'handleMapLoad') as |map|}}
      {{#map.labs-layers
        model=model
        toolTipComponent=(component 'citymap-tooltip')
        onLayerClick=(action 'handleLayerClick') as |layers|}}
        {{#layers.tooltip as |tooltip|}}
          {{tooltip.layer.id}}
        {{/layers.tooltip}}
      {{/map.labs-layers}}
    {{/main-map}}
```

You are able to format the template map-wide. This is a lower-level API, less config-driven. Next step is something outta the box that's config driven.

**Comment by allthesignals** [comment]
What's another API? I could see something like this:

    {{#main-map
      id='main-map'
      initOptions=initMapOptions
      mapLoaded=(action 'handleMapLoad') as |map|}}
      {{#map.labs-layers
        model=model
        toolTipComponent=(component 'citymap-tooltip')
        onLayerClick=(action 'handleLayerClick') as |layers|}}
        {{#layers.tooltip for='layer-id-name' as |tooltip|}}
           {{!-- layer specific template }}
        {{/layers.tooltip}}
      {{/map.labs-layers}}
    {{/main-map}}

When the `for` argument is present, only apply that template to that layer. @chriswhong @andycochran thoughts?

**Comment by allthesignals** [comment]
I guess a component implies reusability and markup freedom. So maybe the second makes more sense.

**Comment by allthesignals** [comment]
Actually this API gets us there:
```handlebars
    {{#main-map
      id='main-map'
      initOptions=initMapOptions
      mapLoaded=(action 'handleMapLoad') as |map|}}
      {{#map.labs-layers
        model=model
        onLayerClick=(action 'handleLayerClick') as |layers|}}
        {{#layers.tooltip for='layer-id-name' as |tooltip|}}
          {{#if (eq tooltip.layer, 'my-special-layer')}}
             {{tooltip.properties.map_pdf_url}}
          {{/if}}
        {{/layers.tooltip}}
      {{/map.labs-layers}}
    {{/main-map}}
```
