### ISSUE TITLE
User can link to PDFs for City Map Alterations

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-citymap#4]
Links are included in a attribute of NYMI dataset.

- [x] Dataset should be modified to include only the filename, not a full path. 

This issue implies hosting of the PDF maps in a publicly accessible place.

- [ ] Approved  Alterations
- [ ] Adopted Alterations (All "Approved and Filed" Maps)

**Comment by allthesignals** [comment]
@aenglis how are these updated? Do their filenames reflect dates?

**Comment by allthesignals** [comment]
@aenglis are files ever replaced or are they only ever added?

**Comment by allthesignals** [comment]
@aenglis are filenames unique?

**Comment by aenglis** [comment]
@allthesignals Today alteration maps are scanned into pdfs as the last step after the map attains adopted status. they are stored on the m drive here: M:\CityMapChanges_AlterationMaps\Alteration_Maps_All. Maps are added to the catalog as they become effective.

**Comment by aenglis** [comment]
@allthesignals The alteration map filenames reflect DCP tracking number for the project. Older alteration maps started with cp numbers and more recent maps use ULURP numbers.

**Comment by allthesignals** [comment]
@aenglis 
> The alteration map filenames reflect DCP tracking number for the project. Older alteration maps started with cp numbers and more recent maps use ULURP numbers.

What system manages this tracking number? Is it in a database somewhere? Could we use that information to pull in other data?

**Comment by aenglis** [comment]
@allthesignals LUCATS tracks this info. It's similar to the zoning index in ZOLA
