### ISSUE TITLE
Tax Lot Intersection

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-citymap#51]
w/ "View in ZoLa" button

**Comment by chriswhong** [comment]
Updates to the popup
- Match LayerGroup title "City Map Amendments" (also modify in layer palette)
- Show Tax Lot with link to ZoLa (Show Boro, block, lot, addreess)
- Call to action to provide feedback

**Comment by andycochran** [comment]
In last week's demo, folks wanted more structure to the PDF Amendments list: 
- [ ] explicitly state that date is effective date
- [ ] App number? 
- [ ] Other meta?

**Comment by chriswhong** [comment]
This issue is complete when the popup also contains information about the lot that is intersected on click (if any), including a link to view that lot in ZoLa
