### ISSUE TITLE
Layer order bug

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-citymap#60]
Layer order should be unchangeable. 

If you turn off/on the "City Map" layer, it appears over the "Street Centerline" layer and the labels are not legible. 

![image](https://user-images.githubusercontent.com/409279/38699029-e99f7984-3e64-11e8-80e7-d4d3fde582a0.png)

**Comment by allthesignals** [comment]
@andycochran is this still true?

**Comment by andycochran** [comment]
I think this bug is gone.
