### ISSUE TITLE
Change name of Amendments layer to "City Map Alterations"

### ISSUE THREAD

**Issue by aenglis** [NYCPlanning/labs-citymap#67]
Re-order layer: move above Arterials layer so that it is fourth in line after pierhead and bulkhead lines layer

**Comment by andycochran** [comment]
Closed by 3834b3ddfa1747bc0af1ed49abe20a273eb77755.

**Comment by andycochran** [comment]
Arterials is fourth. 
<img src="https://user-images.githubusercontent.com/409279/38750062-bbfce94a-3f21-11e8-8f42-ff8acf921615.png" width=300 />

**Comment by aenglis** [comment]
Sorry what I wrote wasn't clear. I meant City Map Alterations layer should be fourth in line and arterials should go below that. For us, the alterations layer is the most important of the two and it should be turned off by default.

**Comment by andycochran** [comment]
Gotcha. Layers have been reordered by 650b3b8d7a604a279578cc066c8d6b64614106af.
