### ISSUE TITLE
How to read an Alteration Map

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-citymap#7]
Annotated "common" alteration map with explanation of symbology and terms...

**Comment by allthesignals** [comment]
Maybe this could also be an interactive step-by-step explainer sequence with arrows, annotations, and highlighting?

**Comment by allthesignals** [comment]
Simplest solution is to have an about page with well-written explanation on alternation map basics as well as a key. Will need to research any possible consistent structure in the PDFs for a true walkthrough.

**Comment by allthesignals** [comment]
We could also use an example PDF and do the walkthrough sequence with that.
