### ISSUE TITLE
Block Search, and Block & Lot Search

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-citymap#8]
- [x] Address Search - Navigation only - pan and zoom
- [ ] Block & Lot Search - Same as ZoLa
- [ ] Block Search - - Same as ZoLa

**Comment by allthesignals** [comment]
Moving "Intersection Search" to its own issue

**Comment by andycochran** [comment]
I'm going to start working on integrating ZoLa's BBL lookup (at least the layout part).
