### ISSUE TITLE
Additional Map Layers

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-citymap#9]
- [x] DTM - (Visualize Lot Boundaries Only)
- [ ] Aerials (ALL OF THEM!)
- [x] Flood Zones 2015 PFIRMS
- [x] Zoning Districts
- [x] Commercial Overlays
- [x] Special Purpose Districts

**Comment by allthesignals** [comment]
This will involve rethinking the ZoLa generic map architecture

**Comment by allthesignals** [comment]
See: https://github.com/allthesignals/mapbox-gl-layer-groups/blob/master/index.js

**Comment by chriswhong** [comment]
Recommend we use MapPLUTO for tax lots for the time being (same as ZoLa)....
